Publish only changed TS components

diff --git a/.github/workflows/publish-components.yaml b/.github/workflows/publish-components.yaml
--- a/.github/workflows/publish-components.yaml
+++ b/.github/workflows/publish-components.yaml
@@ -151,7 +151,8 @@ jobs:
           IFS=$'\n'
           echo "The following files will be published on merge:"
           # Remove initial tsc output
-          for f in $(cat files.txt | sed 1,3d)
+          output_files=$(cat files.txt | sed 1,3d)
+          for f in $output_files
           do
             echo "$f"
           done
@@ -159,30 +160,47 @@ jobs:
           PUBLISHED=""
           ERRORS=""
           SKIPPED=""
-          # included in the components dir, ends with .*js (e.g. .js and .mjs) and not app.js,
-          # doesn't end with /common*.*js, and doesn't follow */common/
-          for f in $(cat files.txt | sed 1,3d); do
-            echo "Checking if $f is publishable"
-            if [[ $f == */components/* ]] && [[ $f == *.*js ]] && [[ $f != *.app.*js ]] \
-              && [[ $f != */common*.*js ]] && [[ $f != */common/* ]]
+          # included in the components dir, ends with .ts and not app.ts,
+          # doesn't end with /common*.ts, and doesn't follow */common/
+          for added_modified_file in "${added_modified_renamed_files[@]}";
+          do
+            echo "Checking if $added_modified_file is a publishable ts file"
+            if [[ $added_modified_file == components/* ]] && [[ $added_modified_file == *.ts ]] && [[ $added_modified_file != *.app.ts ]] \
+                && [[ $added_modified_file != */common*.ts ]] && [[ $added_modified_file != */common/* ]]
             then
-              echo "attempting to publish ${f}"
-              PD_OUTPUT=`./pd publish ${f} --json`
-              if [ $? -eq 0 ]
-              then
-                KEY=`echo $PD_OUTPUT | jq -r ".key"`
-                echo "published ${KEY}"
-                echo "${KEY} will be added to the registry"
-                curl "https://api.pipedream.com/graphql" -H "Content-Type: application/json" -H "Authorization: Bearer ${PD_API_KEY}" --data-binary $'{"query":"mutation($key: String!, $registry: Boolean!, $gitPath: String){\\n  setComponentRegistry(key: $key, registry: $registry, gitPath: $gitPath){\\n    savedComponent{\\n      id\\n      key\\n      gitPath\\n    }\\n  }\\n}","variables":{"key":"'${KEY}'","registry":'true',"gitPath":"'${f}'"}}'
-                PUBLISHED+="*${f}"
-              else
-                ERROR=`echo $PD_OUTPUT | jq -r ".error"`
-                ERROR_MESSAGE="${ERROR} with ${f}"
-                echo $ERROR_MESSAGE
-                ERRORS+="*${ERROR_MESSAGE}"
-                UNPUBLISHED+="*${f}"
-                # add to array to spit out later
-              fi
+              # XXX This is a hacky way to publish only TS components with changes. If a changed
+              # file "path-a/path-b/c.ts" has a corresponding compiled output file
+              # "path-a/dist/path-b/c.mjs", attempt to publish the output `.mjs` file.
+              for f in $output_files; # check each output file for a match
+              do
+                # Replaces /dist/path/filename.mjs with /path/filename.ts
+                maybe_source_file=$(echo "$f" | sed 's/\/dist\//\//;s/.mjs/\.ts/')
+                if [[ ${maybe_source_file} == **/${added_modified_file} ]]
+                then
+                  echo "attempting to publish ${f}"
+                  PD_OUTPUT=`./pd publish ${f} --json`
+                  if [ $? -eq 0 ]
+                  then
+                    KEY=`echo $PD_OUTPUT | jq -r ".key"`
+                    echo "published ${KEY}"
+                    echo "${KEY} will be added to the registry"
+                    curl "https://api.pipedream.com/graphql" -H "Content-Type: application/json" -H "Authorization: Bearer ${PD_API_KEY}" --data-binary $'{"query":"mutation($key: String!, $registry: Boolean!, $gitPath: String){\\n  setComponentRegistry(key: $key, registry: $registry, gitPath: $gitPath){\\n    savedComponent{\\n      id\\n      key\\n      gitPath\\n    }\\n  }\\n}","variables":{"key":"'${KEY}'","registry":'true',"gitPath":"'${f}'"}}'
+                    PUBLISHED+="*${f}"
+                  else
+                    ERROR=`echo $PD_OUTPUT | jq -r ".error"`
+                    ERROR_MESSAGE="${ERROR} with ${f}"
+                    echo $ERROR_MESSAGE
+                    ERRORS+="*${ERROR_MESSAGE}"
+                    UNPUBLISHED+="*${f}"
+                    # add to array to spit out later
+                  fi
+                else
+                  ERROR_MESSAGE="cannot find an output .mjs file with ${f}"
+                  echo $ERROR_MESSAGE
+                  ERRORS+="*${ERROR_MESSAGE}"
+                  UNPUBLISHED+="*${f}"
+                fi
+              done
             else
               echo "${f} will not be added to the registry"
               SKIPPED+="*${f}"
