Update publish-components.yaml

diff --git a/.github/workflows/publish-components.yaml b/.github/workflows/publish-components.yaml
--- a/.github/workflows/publish-components.yaml
+++ b/.github/workflows/publish-components.yaml
@@ -177,36 +177,42 @@ jobs:
               # XXX This is a hacky way to publish only TS components with changes. If a changed
               # file "path-a/path-b/c.ts" has a corresponding compiled output file
               # "path-a/dist/path-b/c.mjs", attempt to publish the output `.mjs` file.
+              changed_output_file = ""
               for f in $output_files; # check each output file for a match
               do
                 # Replaces /dist/path/filename.mjs with /path/filename.ts
                 maybe_source_file=$(echo "$f" | sed 's/\/dist\//\//;s/.mjs/\.ts/')
                 if [[ ${maybe_source_file} == **/${added_modified_file} ]]
                 then
-                  echo "attempting to publish ${f}"
-                  PD_OUTPUT=`./pd publish ${f} --json`
-                  if [ $? -eq 0 ]
-                  then
-                    KEY=`echo $PD_OUTPUT | jq -r ".key"`
-                    echo "published ${KEY}"
-                    echo "${KEY} will be added to the registry"
-                    curl "https://api.pipedream.com/graphql" -H "Content-Type: application/json" -H "Authorization: Bearer ${PD_API_KEY}" --data-binary $'{"query":"mutation($key: String!, $registry: Boolean!, $gitPath: String){\\n  setComponentRegistry(key: $key, registry: $registry, gitPath: $gitPath){\\n    savedComponent{\\n      id\\n      key\\n      gitPath\\n    }\\n  }\\n}","variables":{"key":"'${KEY}'","registry":'true',"gitPath":"'${f}'"}}'
-                    PUBLISHED+="*${f}"
-                  else
-                    ERROR=`echo $PD_OUTPUT | jq -r ".error"`
-                    ERROR_MESSAGE="${ERROR} with ${f}"
-                    echo $ERROR_MESSAGE
-                    ERRORS+="*${ERROR_MESSAGE}"
-                    UNPUBLISHED+="*${f}"
-                    # add to array to spit out later
-                  fi
-                else
-                  ERROR_MESSAGE="cannot find an output .mjs file with ${f}"
-                  echo $ERROR_MESSAGE
-                  ERRORS+="*${ERROR_MESSAGE}"
-                  UNPUBLISHED+="*${f}"
+                  changed_output_file=${f}
+                  break
                 fi
               done
+              if [[ $changed_output_file == "" ]]
+              then
+                ERROR_MESSAGE="cannot find an output .mjs file with ${changed_output_file}"
+                echo $ERROR_MESSAGE
+                ERRORS+="*${ERROR_MESSAGE}"
+                UNPUBLISHED+="*${changed_output_file}"
+              else
+                echo "attempting to publish ${changed_output_file}"
+                PD_OUTPUT=`./pd publish ${changed_output_file} --json`
+                if [ $? -eq 0 ]
+                then
+                  KEY=`echo $PD_OUTPUT | jq -r ".key"`
+                  echo "published ${KEY}"
+                  echo "${KEY} will be added to the registry"
+                  curl "https://api.pipedream.com/graphql" -H "Content-Type: application/json" -H "Authorization: Bearer ${PD_API_KEY}" --data-binary $'{"query":"mutation($key: String!, $registry: Boolean!, $gitPath: String){\\n  setComponentRegistry(key: $key, registry: $registry, gitPath: $gitPath){\\n    savedComponent{\\n      id\\n      key\\n      gitPath\\n    }\\n  }\\n}","variables":{"key":"'${KEY}'","registry":'true',"gitPath":"'${changed_output_file}'"}}'
+                  PUBLISHED+="*${changed_output_file}"
+                else
+                  ERROR=`echo $PD_OUTPUT | jq -r ".error"`
+                  ERROR_MESSAGE="${ERROR} with ${changed_output_file}"
+                  echo $ERROR_MESSAGE
+                  ERRORS+="*${ERROR_MESSAGE}"
+                  UNPUBLISHED+="*${changed_output_file}"
+                  # add to array to spit out later
+                fi
+              fi
             else
               echo "${f} will not be added to the registry"
               SKIPPED+="*${f}"
